import type { Scholar } from "@/types"

export const scholars: Scholar[] = [
  {
    id: "dr-israr-ahmed",
    name: "Dr. Israr Ahmed",
    nameAr: "ڈاکٹر اسرار احمد",
    bio: "Founder of Tanzeem-e-Islami, renowned Islamic scholar, theologian, and Quranic exegete.",
    image: "/images/scholars/dr-israr.jpg",
    channelId: "UCBj6SU_o5wZQJbZJZSkVzOw",
    channelUrl: "https://www.youtube.com/@Official-drisrarahmed",
    featured: true,
    categories: ["tafsir", "seerah", "aqeedah"],
  },
  {
    id: "abu-saad",
    name: "Abu Saad",
    nameAr: "ابو سعد",
    bio: "Islamic speaker known for Quranic reflections and spiritual reminders.",
    image: "/images/scholars/abu-saad.jpg",
    channelId: "UCFvBmxu2ma-f06vTnbX0KiQ",
    channelUrl: "https://www.youtube.com/@AbuSaad",
    featured: true,
    categories: ["tafsir", "spirituality"],
  },
  {
    id: "muhammad-ali",
    name: "Muhammad Ali",
    nameAr: "محمد علی",
    bio: "Islamic content creator focusing on Quranic verses and hadith explanations.",
    image: "/images/scholars/muhammad-ali.jpg",
    channelId: "UC_qJhakG5LqYgVDxIhM0hew",
    channelUrl: "https://www.youtube.com/@MuhammadAlichannel",
    featured: true,
    categories: ["quran", "hadith"],
  },
  {
    id: "tuaha-ibn-jalil",
    name: "Tuaha ibn Jalil",
    nameAr: "توحہ بن جلیل",
    bio: "Islamic speaker known for emotional reminders and stories of the Prophets.",
    image: "/images/scholars/tuaha-ibn-jalil.jpg",
    channelId: "UCN2W4BBQ9gdDfs176CDbR6g",
    channelUrl: "https://www.youtube.com/@TuahaIbnJalil",
    featured: true,
    categories: ["seerah", "spirituality"],
  },
  {
    id: "uthman-ibn-farooq",
    name: "Uthman ibn Farooq",
    nameAr: "عثمان بن فاروق",
    bio: "Islamic speaker and debater known for comparative religion discussions.",
    image: "/images/scholars/uthman-ibn-farooq.jpg",
    channelId: "UC0jXz6YbbOUJ-EZPY1iaaqQ",
    channelUrl: "https://www.youtube.com/@UthmanibnFarooq",
    featured: true,
    categories: ["dawah", "comparative-religion"],
  },
  {
    id: "omar-suleiman",
    name: "Omar Suleiman",
    nameAr: "عمر سليمان",
    bio: "Founder of Yaqeen Institute, Islamic scholar specializing in Islamic theology and spirituality.",
    image: "/images/scholars/omar-suleiman.jpg",
    channelId: "UC3vHW2h22WE-pNi5WJtRIjg",
    channelUrl: "https://www.youtube.com/@yaqeeninstituteofficial",
    featured: true,
    categories: ["tafsir", "spirituality", "seerah"],
  },
  {
    id: "yasir-qadhi",
    name: "Yasir Qadhi",
    nameAr: "ياسر قاضي",
    bio: "Dean of The Islamic Seminary of America, renowned for seerah and Quranic studies.",
    image: "/images/scholars/yasir-qadhi.jpg",
    channelId: "UClUa7-iHJNKEM2e_zWYSPQg",
    channelUrl: "https://www.youtube.com/@YasirQadhi",
    featured: true,
    categories: ["tafsir", "seerah", "aqeedah"],
  },
  {
    id: "mufti-menk",
    name: "Mufti Menk",
    nameAr: "مفتي منك",
    bio: "Grand Mufti of Zimbabwe, one of the most followed Islamic scholars globally.",
    image: "/images/scholars/mufti-menk.jpg",
    channelId: "UCNB_OaI4524fASt8h0IL8dw",
    channelUrl: "https://www.youtube.com/@muftimenkofficial",
    featured: true,
    categories: ["spirituality", "dawah", "fiqh"],
  },
  {
    id: "nouman-ali-khan",
    name: "Nouman Ali Khan",
    nameAr: "نعمان علي خان",
    bio: "Founder and CEO of Bayyinah Institute, renowned for Quranic Arabic and tafsir.",
    image: "/images/scholars/nouman-ali-khan.jpg",
    channelId: "UCRtiU-lpcBSi-ipFKyfIkug",
    channelUrl: "https://www.youtube.com/@bayyinah",
    featured: true,
    categories: ["tafsir", "quranic-arabic"],
  },
  {
    id: "bilal-philips",
    name: "Bilal Philips",
    nameAr: "بلال فيلبس",
    bio: "Islamic scholar and author specializing in Islamic theology and comparative religion.",
    image: "/images/scholars/bilal-philips.jpg",
    channelId: "UCzX0itkJ3Qq1aFdCc9CsRjw",
    channelUrl: "https://www.youtube.com/@bilalphilipsofficial",
    featured: true,
    categories: ["aqeedah", "fiqh", "dawah"],
  },
  {
    id: "zakir-naik",
    name: "Dr. Zakir Naik",
    nameAr: "ذاكر نايك",
    bio: "Founder of Islamic Research Foundation, renowned comparative religion speaker and orator.",
    image: "/images/scholars/zakir-naik.jpg",
    channelId: "UCczZnI6hkhkdvEPwUrQVMcQ",
    channelUrl: "https://www.youtube.com/@Drzakirchannel",
    featured: true,
    categories: ["dawah", "comparative-religion"],
  },
  {
    id: "assim-al-hakeem",
    name: "Assim Al-Hakeem",
    nameAr: "عاصم الحكيم",
    bio: "Saudi-based Islamic scholar known for fatwa sessions and clear explanations of Islamic rulings.",
    image: "/images/scholars/assim-al-hakeem.jpg",
    channelId: "UCWsdcrre0WbCWML_PnuzoAg",
    channelUrl: "https://www.youtube.com/@assimalhakeem",
    featured: true,
    categories: ["fiqh", "aqeedah", "dawah"],
  },
  {
    id: "hamza-yusuf",
    name: "Hamza Yusuf",
    nameAr: "حمزة يوسف",
    bio: "Co-founder of Zaytuna College, leading Western Islamic scholar known for interfaith dialogue and traditional scholarship.",
    image: "/images/scholars/hamza-yusuf.jpg",
    channelId: "UC88lF82aS_VW3oJe7GV5zsA",
    channelUrl: "https://www.youtube.com/@ZaytunaCollege",
    featured: true,
    categories: ["aqeedah", "spirituality", "seerah"],
  },
  {
    id: "belal-assaad",
    name: "Belal Assaad",
    nameAr: "بلال أسعد",
    bio: "Islamic speaker known for emotional lectures on spirituality, family, and self-development.",
    image: "/images/scholars/belal-assaad.jpg",
    channelId: "UC34dxKHa9n9ggxz4m7bztfA",
    channelUrl: "https://www.youtube.com/@BelalAssaad",
    featured: true,
    categories: ["spirituality", "dawah"],
  },
  {
    id: "ali-hammuda",
    name: "Ali Hammuda",
    nameAr: "علي حمودة",
    bio: "Islamic scholar and author based in Wales, UK, known for practical spiritual guidance.",
    image: "/images/scholars/ali-hammuda.jpg",
    channelId: "UC5_hrgirl1FHITUPOYrALVw",
    channelUrl: "https://www.youtube.com/@AliHammuda",
    featured: true,
    categories: ["spirituality", "seerah"],
  },
  {
    id: "youth-club",
    name: "Youth Club",
    nameAr: "یوتھ کلب",
    bio: "Pakistani Islamic organization producing motivational content, podcasts, and scholar interviews.",
    image: "/images/scholars/youth-club.jpg",
    channelId: "UCTedHfyVtctMgTWX2uZkEDQ",
    channelUrl: "https://www.youtube.com/@youthclubpk",
    featured: true,
    categories: ["spirituality", "dawah"],
  },
  {
    id: "raja-ziaul-haq",
    name: "Raja Ziaul Haq",
    nameAr: "راجہ ضیاء الحق",
    bio: "Islamic speaker known for critical analysis of contemporary issues from an Islamic perspective.",
    image: "/images/scholars/raja-ziaul-haq.jpg",
    channelId: "UCFbPWf0TC9uby01Uq0GSuvw",
    channelUrl: "https://www.youtube.com/@MaulviWithAnAttitude",
    featured: true,
    categories: ["dawah", "spirituality"],
  },
  {
    id: "shady-alsuleiman",
    name: "Shady Alsuleiman",
    nameAr: "شادي سليمان",
    bio: "Islamic speaker delivering powerful reminders on faith, family, and contemporary Muslim life.",
    image: "/images/scholars/shady-alsuleiman.jpg",
    channelId: "UCzyHJJAChFMhp_5wLfDd4Ng",
    channelUrl: "https://www.youtube.com/@RemindersFromShadyAlSuleiman",
    featured: false,
    categories: ["spirituality", "dawah"],
  },
  {
    id: "muhammad-alshareef",
    name: "Muhammad Alshareef",
    nameAr: "محمد الشريف",
    bio: "Founder of AlMaghrib Institute, pioneer in modern Islamic dawah and seminary education.",
    image: "/images/scholars/muhammad-alshareef.jpg",
    channelId: "UCg6jDSkhaCgRYAaC7zcsXbw",
    channelUrl: "https://www.youtube.com/@MuhammadAlshareef",
    featured: false,
    categories: ["seerah", "spirituality"],
  },
  {
    id: "almaghrib",
    name: "AlMaghrib Institute",
    nameAr: "معهد المغرب",
    bio: "Islamic education institute offering seminary-level courses on Quran, hadith, fiqh, and seerah.",
    image: "/images/scholars/almaghrib.jpg",
    channelId: "UC1B7kOnMRdPuP0rxW6mS7_A",
    channelUrl: "https://www.youtube.com/@almaghrib",
    featured: false,
    categories: ["tafsir", "hadith", "fiqh", "seerah"],
  },
]
