import type { Scholar } from "@/types"

export const scholars: Scholar[] = [
  {
    id: "dr-israr-ahmed",
    name: "Dr. Israr Ahmed",
    nameAr: "ڈاکٹر اسرار احمد",
    bio: "Founder of Tanzeem-e-Islami, renowned Islamic scholar, theologian, and Quranic exegete.",
    image: "/images/scholars/dr-israr.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@drisrarahmed",
    featured: true,
    categories: ["tafsir", "seerah", "aqeedah"],
  },
  {
    id: "abu-saad",
    name: "Abu Saad",
    nameAr: "ابو سعد",
    bio: "Islamic speaker known for Quranic reflections and spiritual reminders.",
    image: "/images/scholars/abu-saad.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@AbuSaad",
    featured: true,
    categories: ["tafsir", "spirituality"],
  },
  {
    id: "muhammad-ali",
    name: "Muhammad Ali",
    nameAr: "محمد علی",
    bio: "Islamic content creator focusing on Quranic verses and hadith explanations.",
    image: "/images/scholars/muhammad-ali.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@MuhammadAli",
    featured: true,
    categories: ["quran", "hadith"],
  },
  {
    id: "tuaha-ibn-jalil",
    name: "Tuaha ibn Jalil",
    nameAr: "توحہ بن جلیل",
    bio: "Islamic speaker known for emotional reminders and stories of the Prophets.",
    image: "/images/scholars/tuaha-ibn-jalil.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@TuahaibnJalil",
    featured: true,
    categories: ["seerah", "spirituality"],
  },
  {
    id: "uthman-ibn-farooq",
    name: "Uthman ibn Farooq",
    nameAr: "عثمان بن فاروق",
    bio: "Islamic speaker and debater known for comparative religion discussions.",
    image: "/images/scholars/uthman-ibn-farooq.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@UthmanibnFarooq",
    featured: true,
    categories: ["dawah", "comparative-religion"],
  },
  {
    id: "omar-suleiman",
    name: "Omar Suleiman",
    nameAr: "عمر سليمان",
    bio: "Founder of Yaqeen Institute, Islamic scholar specializing in Islamic theology and spirituality.",
    image: "/images/scholars/omar-suleiman.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@OmarSuleiman",
    featured: true,
    categories: ["tafsir", "spirituality", "seerah"],
  },
  {
    id: "yasir-qadhi",
    name: "Yasir Qadhi",
    nameAr: "ياسر قاضي",
    bio: "Dean of The Islamic Seminary of America, renowned for seerah and Quranic studies.",
    image: "/images/scholars/yasir-qadhi.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@YasirQadhi",
    featured: true,
    categories: ["tafsir", "seerah", "aqeedah"],
  },
  {
    id: "mufti-menk",
    name: "Mufti Menk",
    nameAr: "مفتي منك",
    bio: "Grand Mufti of Zimbabwe, one of the most followed Islamic scholars globally.",
    image: "/images/scholars/mufti-menk.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@MuftiMenk",
    featured: true,
    categories: ["spirituality", "dawah", "fiqh"],
  },
  {
    id: "nouman-ali-khan",
    name: "Nouman Ali Khan",
    nameAr: "نعمان علي خان",
    bio: "Founder and CEO of Bayyinah Institute, renowned for Quranic Arabic and tafsir.",
    image: "/images/scholars/nouman-ali-khan.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@NoumanAliKhan",
    featured: true,
    categories: ["tafsir", "quranic-arabic"],
  },
  {
    id: "bilal-philips",
    name: "Bilal Philips",
    nameAr: "بلال فيلبس",
    bio: "Islamic scholar and author specializing in Islamic theology and comparative religion.",
    image: "/images/scholars/bilal-philips.jpg",
    channelId: "UC...",
    channelUrl: "https://www.youtube.com/@BilalPhilips",
    featured: true,
    categories: ["aqeedah", "fiqh", "dawah"],
  },
]
